config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'

  resources :songs
  resources :artists
  resources :rankings, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :rankings, dependent: :destroy
    has_many :songs, through: :rankings
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

app/models/ranking.rb
class Ranking < ApplicationRecord
  belongs_to :song
  belongs_to :artist
end

app/models/song.rb
class Song < ApplicationRecord
    has_many :rankings, dependent: :destroy
    has_many :artists, through: :rankings
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class artistsController < ApplicationController
  before_action :set_artist, only: [:show, :destroy]

  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private
    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:first_name, :last_name)
    end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  before_action :set_course

  def index
    @teachers = @artist.rankings.where(role: 'teacher')
    @tas = @artist.rankings.where(role: 'ta')
    @students = @artist.rankings.where(role: 'student')
  end

  def new
    @ranking = @artist.rankings.new
  end

  def create
    @ranking = @artist.rankings.new(ranking_params)
    if @ranking.save
      redirect_to artist_rankings_path(@artist)
    else
      render :new
    end
  end

  def destroy
    @ranking = @artist.rankings.find(params[:id])
    @ranking.destroy
    redirect_to artist_rankings_path(@artist)
  end

 private
   def set_artist
     @artist = Artist.find(params[:artist_id]) 
   end

   def ranking_params
     params.require(:ranking).permit(:role, :user_id)
   end
end

app/controllers/songs_controller.rb
class songsController < ApplicationController
  before_action :set_song, only: [:show, :destroy]

  def index
    @songs = Song.all
  end

  def show
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.create(song_params)

    if @song.save
      redirect_to @song
    else
      render :new
    end
  end

  def destroy
    @song.destroy
    redirect_to songs_path
  end

  private
    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<%= link_to 'Add Artist', new_artist_path %>
<hr />
<h2><%= @artists.length <= 0 ? "No Artists" : "" %></h2> 
<ul>
  <% @artists.each do |artist| %>
    <li>
      <%= link_to artist.name, artist %>
    </li>
  <% end %>
</ul>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<%= form_with(model: @artist, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Artist Name" %>
  </div>
  <%= f.submit nil, class: "ui blue button inverted" %>
<% end %>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<hr />
<br />
<%= link_to 'rankings', course_rankings_path(@course), class: "ui primary button inverted" %>
<br />
<br />
<br />
<%= link_to "Delete Course", @course, method: :delete, class: "ui red button inverted" %>
 

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <li>
      <%= link_to 'Artists', artists_path %>
    </li>
    <li>
      <%= link_to 'Add Artist', new_artist_path %>
    </li>
    <li>
      <%= link_to 'Songs', songs_path %>
    </li>
    <li>
      <%= link_to 'Add song', new_song_path %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicOne</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class="ui container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/rankings/index.html.erb
<h1><%= @artist.name %>: Rankings</h1>
<%= link_to 'Add Ranking', new_artist_ranking_path(@artist) %>
<hr />

<h2>Teacher</h2>
<ul>
  <% @teachers.each do |teacher| %>
    <li>
      <%= teacher.user.full_name %>
      <br />
      <%= link_to 'Remove', artist_ranking_path(@artist, teacher), method: :delete %>
    </li>
  <% end %>
</ul>
<h2>Ta</h2>
<ul>
  <% @tas.each do |ta| %>
    <li>
      <%= ta.user.full_name %>
      <br />
      <%= link_to 'Remove', artist_ranking_path(@artist, ta), method: :delete %>
    </li>
 <% end %>
</ul>
<h2>Student</h2>
<ul>
  <% @students.user.each do |student| %>
    <li>
      <%= student.user.full_name %>
      <br />
      <%= link_to 'Remove', artist_ranking_path(@artist, student), method: :delete %>
   </li>
 <% end %>
</ul>

app/views/rankings/new.html.erb
<h1>Rankings#new</h1>
<%= form_with(model: [@artist, @ranking], local: true, class: "ui form" ) do |f| %>
  <%= f.label :song %>
  <%= f.select :song_id, @songs.collect { |u| [u.artist, u.id] } %>
  <br />
  <%= f.label :role %>
  <%= f.select :role, ['ta', 'teacher', 'student'] %>
  <br />
  <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<%= link_to 'Add Song', new_song_path %>
<hr />
<ul>
  <% @songs.each do |song| %>
    <li>
      <%= link_to song.full_name, song %>
    </li>
<% end %>
</ul>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<%= form_with(model: @song, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :first_name, required: true, autofocus: true, placeholder: "First Name" %>
  </div>
  <div class="field">
    <%= f.label :song %>
    <%= f.text_field :song, required: true, placeholder: "Last Name" %>
  </div>
  <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<h1><%= @song.full_name %></h1>
<hr />
<h2>Courses</h2>
<ul>
  <% @song.courses.each do |course| %>
    <li>
      <%= link_to course.name, course %>
    </li>
  <% end %>
</ul>
<br />
<br />
<br />
<%= link_to 'Delete song', @song, method: :delete, class: "ui red button inverted" %>